---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: frontend-secrets
  namespace: nextjs-template
spec:
  encryptedData:
    DEMO_SECRET_MESSAGE: AgCgEZbWQM7yW4DcSFHAz2C40K1Xl7Tzy78uEb289lQi2ANogVQ4OEN6IPhwANEfRkUOWOnK5a1o1J9PXMVOmY8uvdOVTmP80rZbByo0plm6lMoC/GZ5Szq6lssx/U7cmP+wIUkFhts0J2mXEZ5DWcAgBlkmqgAbxzd1anXZme4dYnBCrxpbIGWFT/s6EQfwgyyxLLp73/OhnwJpEZCXsvvBM34b/V5Jo2eRGSnkqfy0+eNm9X40jk0srPXGoO01r9YGGNU6w99A7Nam8gb5qReFoqR1qT2zN/YST54D81EqCsMX/cKekCBHqDtLO2gB0IiOavMlOhRn7I84G2xt25dnd7r2RH696RtuzQ45igpjYkjEwuueya9yECr7hSKpJ8GchOFWgidZ8Ia5a9raijNlRyvHTCzG0AntMeJcNGo+ebO72nvsmrXFx/s50KDLMs2nQG1I0VSquiXMn4y0so4LV2UJXPdMUZ05/BI0oI1GyWagW0ljv5YWAu9HsAde7mi8qIeCfqCGEY+1nehx34Zbv8QMjkFVeT6C0ANGr3UlsCCp5TyDqaShbRxSuTSaebqe2lzBEg0tDh3X1GPdsTo9wX2WgDI6bGt3f+xpIwHxMqiW2YdZeY0+HCKNMunZRSXClYqHFd+Qv8PEo2pj50/dy2Bvg9eAHSYNlG9luNRz77dielDfaU7DR1/9a0Cb1e7Aangj6NG3PTZFNWsEQNkdoglT9VJn+IAiMw8haLm7s8b39S8MWm4=
  template:
    metadata:
      name: frontend-secrets
      namespace: nextjs-template
